### ISSUE TITLE
[FEATURE REQUEST] WinSxS filemap name generation support

### ISSUE THREAD

**Issue by pivotman319-owo** [Gamers-Against-Weed/haveSxS#1]
Would be nice to have support for cdf-ms cbs filename generation. Friend and I are working on a script that recovers the full names and dirpaths of SxS langpack components from a WIM's [DELETED] dir (case in point: 6.1.6941.0 (fbl_srv.081102-0300)), and there's a bunch of files within the WIM itself that appear to have the PcmH header, of which belong to the WinSxS\FileMaps directory.

[Sample file from 6941 - `$$_system32_tk-tm_5f1dc9625a1afcad.cdf-ms` (rename extension to .cdf-ms)](https://github.com/Gamers-Against-Weed/haveSxS/files/11183304/_system32_tk-tm_5f1dc9625a1afcad.txt)

**Comment by nekoppai** [comment]
I don't think it makes sense to bother with these files since they are automatically generated when installing a package. It would probably only be useful if you were making your own servicing stack.

**Comment by pivotman319-owo** [comment]
> I don't think it makes sense to bother with these files since they are automatically generated when installing a package. It would probably only be useful if you were making your own servicing stack.

figured as much, only fully learned how to [properly stage a build from scratch](https://cdn.discordapp.com/attachments/891040979983958086/1128251858679504916/image.png) like a month ago (with the help of your tools ofc; as well as understand why NT bugchecks or behaves weirdly if you don't deal with certain things first such as manifest decompression pre-v1903 or Set-SkuIntlDefaults on lps other than en-US) and found out that sxs filemaps are actually autogenerated by panther/cbs during edition staging. sorry for bothering you, only realized I filed this issue like several months ago and didn't know you replied until now.

have a good one!
